<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Cleaning" Id="{ee15386c-44bc-46bd-a7f8-580ac15c0d3e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Cleaning
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Cleaning">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>